### ISSUE TITLE
链接放错了 淦

### ISSUE THREAD

**Issue by TheInterestingSoul** [manoil/manoil#1]
> Ask me a question: [Open an issue here.](https://github.com/TheInterestingSoul/TheInterestingSoul/issues/new)

```
https://github.com/TheInterestingSoul/TheInterestingSoul/issues/new
```

你得用`manoil`替换掉我的名字，不然已经有人点错了

**Comment by TheInterestingSoul** [comment]
直接fork可还行

**Comment by manoil** [comment]
> 直接fork可还行

哈哈哈哈哈哈哈草 忘记了
